import { useState } from 'react';
import { Download, Copy, Check, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import type { SeoScanRun, SeoPsiResult, SeoIssue } from '@/types/seo';
import { format } from 'date-fns';

interface ExportButtonProps {
  scan: SeoScanRun;
  results: SeoPsiResult[];
  issues: SeoIssue[];
  projectName: string;
  projectDomain: string;
}

function generateMarkdownReport(
  scan: SeoScanRun,
  results: SeoPsiResult[],
  issues: SeoIssue[],
  projectName: string,
  projectDomain: string
): string {
  const mobileResults = results.filter(r => r.strategy === 'mobile');
  const desktopResults = results.filter(r => r.strategy === 'desktop');
  
  const avgScore = (scores: (number | null)[]) => {
    const valid = scores.filter((s): s is number => s !== null);
    return valid.length > 0 ? Math.round(valid.reduce((a, b) => a + b, 0) / valid.length) : 'N/A';
  };

  const groupedIssues = {
    P0: issues.filter(i => i.priority === 'P0'),
    P1: issues.filter(i => i.priority === 'P1'),
    P2: issues.filter(i => i.priority === 'P2'),
  };

  let md = `# SEO Audit Report: ${projectName}

**Domain:** ${projectDomain}
**Scan Date:** ${format(new Date(scan.created_at), 'MMMM d, yyyy HH:mm')}
**URLs Scanned:** ${scan.urls_scanned}
**Status:** ${scan.status}

---

## Performance Summary

### Mobile Scores
| Metric | Average Score |
|--------|---------------|
| Performance | ${avgScore(mobileResults.map(r => r.performance_score))} |
| Accessibility | ${avgScore(mobileResults.map(r => r.accessibility_score))} |
| Best Practices | ${avgScore(mobileResults.map(r => r.best_practices_score))} |
| SEO | ${avgScore(mobileResults.map(r => r.seo_score))} |

### Desktop Scores
| Metric | Average Score |
|--------|---------------|
| Performance | ${avgScore(desktopResults.map(r => r.performance_score))} |
| Accessibility | ${avgScore(desktopResults.map(r => r.accessibility_score))} |
| Best Practices | ${avgScore(desktopResults.map(r => r.best_practices_score))} |
| SEO | ${avgScore(desktopResults.map(r => r.seo_score))} |

---

## Issues Found

**Total Issues:** ${issues.length}
- Critical (P0): ${groupedIssues.P0.length}
- High (P1): ${groupedIssues.P1.length}
- Medium (P2): ${groupedIssues.P2.length}

`;

  if (groupedIssues.P0.length > 0) {
    md += `\n### Critical Issues (P0)\n\n`;
    groupedIssues.P0.forEach((issue, i) => {
      md += `#### ${i + 1}. ${issue.title}\n`;
      md += `**Category:** ${issue.category}\n\n`;
      if (issue.description) md += `${issue.description}\n\n`;
      if (issue.fix_steps.length > 0) {
        md += `**How to fix:**\n`;
        issue.fix_steps.forEach((step, j) => {
          md += `${j + 1}. ${step}\n`;
        });
        md += '\n';
      }
    });
  }

  if (groupedIssues.P1.length > 0) {
    md += `\n### High Priority Issues (P1)\n\n`;
    groupedIssues.P1.forEach((issue, i) => {
      md += `#### ${i + 1}. ${issue.title}\n`;
      md += `**Category:** ${issue.category}\n\n`;
      if (issue.description) md += `${issue.description}\n\n`;
      if (issue.fix_steps.length > 0) {
        md += `**How to fix:**\n`;
        issue.fix_steps.forEach((step, j) => {
          md += `${j + 1}. ${step}\n`;
        });
        md += '\n';
      }
    });
  }

  if (groupedIssues.P2.length > 0) {
    md += `\n### Medium Priority Issues (P2)\n\n`;
    groupedIssues.P2.forEach((issue) => {
      md += `- **${issue.title}** (${issue.category}): ${issue.description || 'No description'}\n`;
    });
  }

  md += `\n---\n\n*Generated by SEO Copilot on ${format(new Date(), 'MMMM d, yyyy HH:mm')}*\n`;

  return md;
}

export function ExportButton({ scan, results, issues, projectName, projectDomain }: ExportButtonProps) {
  const [copied, setCopied] = useState(false);

  const markdown = generateMarkdownReport(scan, results, issues, projectName, projectDomain);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `seo-audit-${projectDomain.replace(/[^a-z0-9]/gi, '-')}-${format(new Date(scan.created_at), 'yyyy-MM-dd')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline">
          <FileText className="h-4 w-4 mr-2" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleCopy}>
          {copied ? (
            <>
              <Check className="h-4 w-4 mr-2 text-green-500" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="h-4 w-4 mr-2" />
              Copy as Markdown
            </>
          )}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleDownload}>
          <Download className="h-4 w-4 mr-2" />
          Download .md file
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
