/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EnhancedAiRouteImport } from './routes/enhanced-ai'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromptLibraryRouteImport } from './routes/prompt-library'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as RagLabRouteImport } from './routes/rag-lab'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as SeoAuditScanRunIdRouteImport } from './routes/seo-audit/$scanRunId'
import { Route as SeoProjectsIndexRouteImport } from './routes/seo-projects/index'
import { Route as SeoProjectsIdRouteImport } from './routes/seo-projects/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnhancedAiRoute = EnhancedAiRouteImport.update({
  id: '/enhanced-ai',
  path: '/enhanced-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLibraryRoute = PromptLibraryRouteImport.update({
  id: '/prompt-library',
  path: '/prompt-library',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const RagLabRoute = RagLabRouteImport.update({
  id: '/rag-lab',
  path: '/rag-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAuditScanRunIdRoute = SeoAuditScanRunIdRouteImport.update({
  id: '/seo-audit/$scanRunId',
  path: '/seo-audit/$scanRunId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoProjectsIndexRoute = SeoProjectsIndexRouteImport.update({
  id: '/seo-projects/',
  path: '/seo-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoProjectsIdRoute = SeoProjectsIdRouteImport.update({
  id: '/seo-projects/$id',
  path: '/seo-projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/enhanced-ai': typeof EnhancedAiRoute
  '/paths': typeof PathsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prompt-library': typeof PromptLibraryRoute
  '/prompts': typeof PromptsRoute
  '/rag-lab': typeof RagLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/seo-audit/$scanRunId': typeof SeoAuditScanRunIdRoute
  '/seo-projects/$id': typeof SeoProjectsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/seo-projects/': typeof SeoProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/enhanced-ai': typeof EnhancedAiRoute
  '/paths': typeof PathsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prompt-library': typeof PromptLibraryRoute
  '/prompts': typeof PromptsRoute
  '/rag-lab': typeof RagLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/seo-audit/$scanRunId': typeof SeoAuditScanRunIdRoute
  '/seo-projects/$id': typeof SeoProjectsIdRoute
  '/blog': typeof BlogIndexRoute
  '/seo-projects': typeof SeoProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/enhanced-ai': typeof EnhancedAiRoute
  '/paths': typeof PathsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prompt-library': typeof PromptLibraryRoute
  '/prompts': typeof PromptsRoute
  '/rag-lab': typeof RagLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/seo-audit/$scanRunId': typeof SeoAuditScanRunIdRoute
  '/seo-projects/$id': typeof SeoProjectsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/seo-projects/': typeof SeoProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/docs'
    | '/enhanced-ai'
    | '/paths'
    | '/pricing'
    | '/privacy'
    | '/prompt-library'
    | '/prompts'
    | '/rag-lab'
    | '/sitemap.xml'
    | '/subscription'
    | '/terms'
    | '/blog/$slug'
    | '/seo-audit/$scanRunId'
    | '/seo-projects/$id'
    | '/blog/'
    | '/seo-projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/docs'
    | '/enhanced-ai'
    | '/paths'
    | '/pricing'
    | '/privacy'
    | '/prompt-library'
    | '/prompts'
    | '/rag-lab'
    | '/sitemap.xml'
    | '/subscription'
    | '/terms'
    | '/blog/$slug'
    | '/seo-audit/$scanRunId'
    | '/seo-projects/$id'
    | '/blog'
    | '/seo-projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/auth'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/docs'
    | '/enhanced-ai'
    | '/paths'
    | '/pricing'
    | '/privacy'
    | '/prompt-library'
    | '/prompts'
    | '/rag-lab'
    | '/sitemap.xml'
    | '/subscription'
    | '/terms'
    | '/blog/$slug'
    | '/seo-audit/$scanRunId'
    | '/seo-projects/$id'
    | '/blog/'
    | '/seo-projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiRoute: typeof ApiRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  EnhancedAiRoute: typeof EnhancedAiRoute
  PathsRoute: typeof PathsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PromptLibraryRoute: typeof PromptLibraryRoute
  PromptsRoute: typeof PromptsRoute
  RagLabRoute: typeof RagLabRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SeoAuditScanRunIdRoute: typeof SeoAuditScanRunIdRoute
  SeoProjectsIdRoute: typeof SeoProjectsIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SeoProjectsIndexRoute: typeof SeoProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enhanced-ai': {
      id: '/enhanced-ai'
      path: '/enhanced-ai'
      fullPath: '/enhanced-ai'
      preLoaderRoute: typeof EnhancedAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-library': {
      id: '/prompt-library'
      path: '/prompt-library'
      fullPath: '/prompt-library'
      preLoaderRoute: typeof PromptLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rag-lab': {
      id: '/rag-lab'
      path: '/rag-lab'
      fullPath: '/rag-lab'
      preLoaderRoute: typeof RagLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-audit/$scanRunId': {
      id: '/seo-audit/$scanRunId'
      path: '/seo-audit/$scanRunId'
      fullPath: '/seo-audit/$scanRunId'
      preLoaderRoute: typeof SeoAuditScanRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-projects/': {
      id: '/seo-projects/'
      path: '/seo-projects'
      fullPath: '/seo-projects/'
      preLoaderRoute: typeof SeoProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-projects/$id': {
      id: '/seo-projects/$id'
      path: '/seo-projects/$id'
      fullPath: '/seo-projects/$id'
      preLoaderRoute: typeof SeoProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiRoute: ApiRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  EnhancedAiRoute: EnhancedAiRoute,
  PathsRoute: PathsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PromptLibraryRoute: PromptLibraryRoute,
  PromptsRoute: PromptsRoute,
  RagLabRoute: RagLabRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  SeoAuditScanRunIdRoute: SeoAuditScanRunIdRoute,
  SeoProjectsIdRoute: SeoProjectsIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  SeoProjectsIndexRoute: SeoProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
