// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zguwfogavvdsbujiakko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndXdmb2dhdnZkc2J1amlha2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTIxMzQsImV4cCI6MjA2NTQ2ODEzNH0.T94nJbbkG7AYB8Q56N2-grSm-7iqiG9GV7_HR-ufBaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);